config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-cerulean-uakari.sh
        container: qc.acc_squirrely-mauve-dachshund
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-crimson-albatross.sh
        container: qc.doc_lovely-amethyst-stoat
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-lilac-shark.sh
        container: qc.doc_muggy-sapphire-dogfish
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-teal-cheetah.sh
        container: qc.doc_snoopy-corn-chow
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-chocolate-lemur.sh
        container: qc.lic_nerdy-carmine-kakapo
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-vermilion-bongo.sh
        container: qc.sec_stealthy-amber-warthog
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homely-jade-elephant.sh
        container: qc.sty_stealthy-bistre-hare
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d commands:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-corn-vulture.sh
        container: qc.uni_sleepy-linen-barnacle
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-lavender-moorhen.sh
        container: qc.ver_clammy-ochre-panda
timeout: 5400
