config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d:
      branch: master
      repo: https://gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-silver-cougar.sh
        container: qc.acc_dorky-malachite-russel
  QC.Doc:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cyan-hedgehog.sh
        container: qc.doc_nippy-chocolate-weasel
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.beady-pumpkin-snail.sh
        container: qc.doc_scummy-sepia-labradoodle
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-maroon-gar.sh
        container: qc.doc_snoopy-puce-newt
  QC.Lic:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-azure-angelfish.sh
        container: qc.lic_sleazy-lime-bird
  QC.Sec:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lavender-chinook.sh
        container: qc.sec_hazy-tan-spider
  QC.Sty:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-pink-swan.sh
        container: qc.sty_jumpy-salmon-chicken
  QC.Uni:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d commands:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-goldenrod-kangaroo.sh
        container: qc.uni_homey-harlequin-swan
  QC.Ver:
    repos:
      gitlab.geo3bcn.csic.es/dtgeo_geo3bcn/dtc-v2/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-periwinkle-monster.sh
        container: qc.ver_paltry-apricot-squid
timeout: 5400
