config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.1.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/fall3d-suite/fall3d:
      branch: master
      repo: https://gitlab.com/fall3d-suite/fall3d.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-harlequin-capybara.sh
        container: qc.acc_cloudy-saffron-affenpinscher
  QC.Doc:
    repos:
      gitlab.com/fall3d-suite/fall3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-magenta-beetle.sh
        container: qc.doc_seedy-mustard-opossum
      gitlab.com/fall3d-suite/fall3d git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-gamboge-toucan.sh
        container: qc.doc_sleazy-celadon-lion
      gitlab.com/fall3d-suite/fall3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-coral-whale.sh
        container: qc.doc_nippy-periwinkle-raccoon
  QC.Lic:
    repos:
      gitlab.com/fall3d-suite/fall3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-lemon-lion.sh
        container: qc.lic_crabby-cerulean-balinese
  QC.Met:
    repos:
      gitlab.com/fall3d-suite/fall3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-razzmatazz-baboon.sh
        container: qc.met_bumpy-apricot-mouse
  QC.Sec:
    repos:
      gitlab.com/fall3d-suite/fall3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-taupe-caterpillar.sh
        container: qc.sec_flabby-wisteria-hippopotamus
  QC.Sty:
    repos:
      gitlab.com/fall3d-suite/fall3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-xanthic-frigatebird.sh
        container: qc.sty_crabby-amaranth-robin
      gitlab.com/fall3d-suite/fall3d jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-aqua-dachshund.sh
        container: qc.sty_scanty-burgundy-fish
  QC.Uni:
    repos:
      gitlab.com/fall3d-suite/fall3d pytest:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-turquoise-cuttlefish.sh
        container: qc.uni_craggy-ochre-guppy
  QC.Ver:
    repos:
      gitlab.com/fall3d-suite/fall3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tomato-axolotl.sh
        container: qc.ver_queasy-myrtle-barb
timeout: 5400
